import react from "@vitejs/plugin-react";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "happy-dom",
    setupFiles: ["test/setup.ts"],
    env: {
      NEXT_PUBLIC_SITE_URL: "https://example.com",
    },
    include: [
      "app/**/*.test.{ts,tsx}",
      "components/**/*.test.{ts,tsx}",
      "lib/**/*.test.{ts,tsx}",
      "db/**/*.test.ts",
    ],
    coverage: {
      provider: "v8",
      include: [
        "app/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
        "lib/**/*.ts",
        "db/**/*.ts",
      ],
      exclude: [
        "**/*.test.{ts,tsx}",
        "**/*.d.ts",
        // Auth / Stripe / DB wiring — integration surface, not unit-covered
        "lib/better-auth/**",
        "lib/stripe/**",
        "lib/subscription/**",
        "lib/email/**",
        "lib/db/**",
        "lib/e2e/**",
        "lib/notes/**",
        "lib/notifications/**",
        "lib/hooks/**",
        "lib/notify.ts",
        "lib/dashboard/**",
        "lib/admin/**",
        "lib/config/**",
        "lib/security/**",
        "lib/help/support-tickets.ts",
        "lib/help/client-ip.ts",
        "lib/help/help-bot-prompt.ts",
        "lib/analytics/funnel-events.ts",
        "lib/analytics/cookie-consent-context.tsx",
        "lib/i18n/metadata.ts",
        "lib/i18n/page-intl.ts",
        "lib/i18n/messages.ts",
        "lib/seo/json-ld.ts",
        "lib/pwa/config.ts",
        "lib/legal/types.ts",
        "lib/legal/documents/**",
        "lib/docs/**",
        "db/schema.ts",
        "db/index.ts",
        "app/api/**",
        "app/actions/**",
        "app/login/**",
        "app/signup/**",
        "app/forgot-password/**",
        "app/reset-password/**",
        "app/dashboard/**",
        "app/privacy/**",
        "app/terms/**",
        "app/cookies/**",
        "app/help/**",
        "app/llms.txt/**",
        "app/manifest.ts",
        "app/layout.tsx",
        "app/providers.tsx",
        "app/page.tsx",
        "app/pricing/**",
        "app/robots.ts",
        "app/sitemap.ts",
        "app/icon.tsx",
        "app/opengraph-image.tsx",
        "lib/api-error.ts",
        "lib/resolve-origin.ts",
        "lib/app-version.ts",
        "lib/i18n/faq/**",
        "lib/seo/canonical-host.ts",
        "components/auth/**",
        "components/dashboard/**",
        "components/admin/**",
        "components/help/**",
        "components/legal/**",
        "components/analytics/**",
        "components/i18n/**",
        "components/theme/theme-provider.tsx",
        "components/theme/theme-toggle.tsx",
        "components/pwa/**",
        "components/push/**",
        "components/tutorial/**",
        "components/marketing/**",
        "components/layout/**",
        "components/ui/**",
        "components/docs/**",
      ],
      reporter: ["text", "text-summary", "lcov", "json-summary"],
      reportsDirectory: "coverage",
      thresholds: {
        lines: 90,
        branches: 80,
        functions: 90,
        statements: 90,
      },
    },
  },
  resolve: {
    alias: {
      "@": projectRoot,
    },
  },
});
