/** Placeholder brand — replace with your product name before shipping. */
export const BRAND_NAME = "SaaS Template";
export const BRAND_SLUG = "saas-template";
export const BRAND_TAGLINE = "Ship your SaaS in days, not months.";

export const BRAND_LOGO_SIZE = {
  SM: 60,
  MD: 140,
  LG: 200,
} as const;

/**
 * Generated by `app/opengraph-image.tsx` / `app/icon.tsx`.
 * Swap those files (or point these at static assets under `public/`) for real brand art.
 */
export const BRAND_OG_IMAGE = "/opengraph-image";
export const BRAND_ICON = "/icon";
